version: '3'
services:
  webserver:
    image: webserver:latest
    container_name: webserver
    ports:
      - "80:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USERNAME=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"